### ISSUE TITLE
Rework some tests when we switch to a cime version that has nuopc as the default

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1478]
When we switch to a cime version that has nuopc as the default (cime6.0.8 or later; planned for cesm2_3_beta06), we should make some changes to the test suite:

- [ ] Tests that are currently `_Vnuopc` should be changed to `_Vmct`.
- [ ] The USUMB test uses different testmods for nuopc vs. mct. Make sure each USUMB test is using the correct testmod
- [ ] Change any occurrences of _N2 to _C2 (and other _N# if there are any), except leaving _N2 for any _Vmct tests
- [ ] For tests that are currently failing with the nuopc driver, temporarily add mct versions so that we are testing those configurations until we can get them passing with nuopc.
- [ ] It looks like the `SMS_Ld5_D_P48x1_Vnuopc.f10_f10_mg37.IHistClm51Bgc.izumi_nag.clm-decStart` test can be removed from the expected fails list, and issue #1317 can possibly be closed.

**Comment by billsacks** [comment]
@ekluzek @mvertens @fischer-ncar @jedwards4b - I ran the aux_clm test suite with the externals that I think are planned for cesm2_3_beta06 (the version @fischer-ncar was using before he backed cime off to a version that doesn't use nuopc by default). Things are looking pretty good. Here are the failures I got:

### CMIP6 configurations fail in SHAREDLIB_BUILD

This is a known issue: `Variable 'histaux_l2x1yrg' from file 'user_nl_cpl' is not in the namelist definition`

This affects the following tests:
- `SMS_Lm1.f10_f10_mg37.I1850Clm50BgcCropCmip6waccm.cheyenne_gnu.clm-basic`
- `ERS_Ly3.f10_f10_mg37.I1850Clm50BgcCropCmip6.cheyenne_intel.clm-basic`
- `SMS_Ld2_D.f09_g17.I1850Clm50BgcCropCmip6.cheyenne_intel.clm-basic_interp`
- `SMS_Lm1.f19_g17.I1850Clm50BgcCropCmip6waccm.cheyenne_intel.clm-basic`

### DAE test fails (known issue)

`DAE_N2_D_Lh12.f10_f10_mg37.I2000Clm50BgcCrop.cheyenne_intel.clm-DA_multidrv` fails due to https://github.com/escomp/cmeps/issues/175

### Other multi-instance failures

These multi-instance tests time out. It seems like maybe they are hanging. This could be the same issue as the DAE test failure. It's possible that we just need to change these to `_C2` instead of `_N2`. I'm running these tests with `_C2` now and will post an update when they are complete:
- `ERI_N2_Ld9.f19_g17.I2000Clm51BgcCrop.cheyenne_intel.clm-default`
- `SMS_N2_D_Lh12.f09_g17.I2000Clm50Sp.cheyenne_intel.clm-pauseResume`

### USUMB test

This seems to be a new issue with the latest externals: The USUMB tests (e.g., `SMS_D_Lm1_Mmpi-serial_Vnuopc.CLM_USRDAT.I1PtClm50SpRs.cheyenne_intel.clm-USUMB_nuopc`) are failing in the submit stage with:

```
Traceback (most recent call last):
  File "./case.submit", line 130, in <module>
    _main_func(__doc__)
  File "./case.submit", line 127, in _main_func
    batch_args=batch_args, workflow=workflow, chksum=chksum)
  File "/glade/work/sacks/ctsm_code/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 209, in submit
    is_batch=is_batch)
  File "/glade/work/sacks/ctsm_code/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1887, in run_and_log_case_status
    rv = func()
  File "/glade/work/sacks/ctsm_code/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 206, in <lambda>
    chksum=chksum)
  File "/glade/work/sacks/ctsm_code/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 133, in _submit
    case.check_case(skip_pnl=skip_pnl, chksum=chksum)
  File "/glade/work/sacks/ctsm_code/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 224, in check_case
    self.check_all_input_data(chksum=chksum)
  File "/glade/work/sacks/ctsm_code/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 173, in check_all_input_data
    attributes={"CLM_USRDAT_NAME":clm_usrdat_name})
  File "/glade/work/sacks/ctsm_code/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 197, in _downloadfromserver
    protocol, address, user, passwd, _, ic_filepath, _ = inputdata.get_next_server(attributes=attributes)
  File "/glade/work/sacks/ctsm_code/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/XML/inputdata.py", line 44, in get_next_server
    self._servernode = servernodes[0]
IndexError: list index out of range
```

### izumi pgi tests

Both of our izumi pgi tests fail at runtime with `Object being used before creation`. This affects:
- `SMS_D.f10_f10_mg37.I2000Clm51BgcCrop.izumi_pgi.clm-crop`
- `SMS.f10_f10_mg37.I2000Clm50BgcCrop.izumi_pgi.clm-crop`

**Comment by mvertens** [comment]
@billsacks - thanks so much for doing this and for the summary. @jedwards4b - can you please look at the USUMB test failures. I am wondering if these are due to the changes I made to have modify the cdeps stream_xxx.xml file via user_nl_xxx_streams.

**Comment by mvertens** [comment]
@jedwards4b - also can you please look at the multi-instance tests and determine if we need to change _N2 to _C2. Thanks!

**Comment by billsacks** [comment]
@mvertens @jedwards4b I'm running these tests with `_C2` now to see if that fixes the issue.

I should add that, in summary, none of these issues feel like show-stoppers to me: I would be comfortable updating to the latest externals and nuopc by default with this small set of expected failures – though of these failures, the USUMB one is probably highest priority to solve (and hopefully won't be too hard).

Great work to @mvertens , @jedwards4b , @ekluzek and everyone else who has worked so hard to get everything working with nuopc/cmeps/cdeps!!!

**Comment by jedwards4b** [comment]
The USUMB test issue is fixed in https://github.com/ESMCI/cime/pull/4081

**Comment by jedwards4b** [comment]
The _N option is not supported by the nuopc driver. I have updated the test_scheduler to reflect this in https://github.com/ESMCI/cime/pull/4082

**Comment by billsacks** [comment]
Thanks @jedwards4b ! (I'm still waiting for the `_C2` versions of these tests to launch).

**Comment by billsacks** [comment]
Changing the _N2 tests to _C2 doesn't solve the problem: these tests still time out at 20 min (which should be more than enough time) with the nuopc driver:
- ERI_C2_Ld9.f19_g17.I2000Clm51BgcCrop.cheyenne_intel.clm-default
- SMS_C2_D_Lh12.f09_g17.I2000Clm50Sp.cheyenne_intel.clm-pauseResume

See /glade/scratch/sacks/tests_0903-104735ch

Again, I don't feel this is critical to resolve before switching to nuopc as the default, but would be good to figure out before too long.

**Comment by jedwards4b** [comment]
@mvertens Can we just remove the pauseResume until there is support for that functionality?

**Comment by mvertens** [comment]
@jedwards4b - my understanding is that CTSM actually needs multi-instance functionality. So I am fine dropping the pause resume for now - but I think we still need to understand why the ERI_C2_Ld9.f19_g17.I2000Clm51BgcCrop.cheyenne_intel.clm-default is timing out and fix that. I'm happy to work with you on that next week.

**Comment by jedwards4b** [comment]
I didn't say anything about dropping the other test.

**Comment by billsacks** [comment]
My initial guess (without having looked into it at all) would be that the two tests I mentioned recently are failing for the same reason as the DAE test, in which case some of the discussion in https://github.com/ESCOMP/CMEPS/issues/175 may be relevant. In particular, @jedwards4b seemed to suspect something in the reading / writing of restart / finidat_interp_dest files, and indeed it seems like the slowness in /glade/scratch/sacks/tests_0903-104735ch/SMS_C2_D_Lh12.f09_g17.I2000Clm50Sp.cheyenne_intel.clm-pauseResume.0903-104735ch/run may be happening at that point.

**Comment by jedwards4b** [comment]
I wonder if performance would be improved if we separate output from each model instance into run_0001, run_0002 etc.
