### ISSUE TITLE
Interim restart work: ERR...clm-default tests fail COMPARE_base_rest (missing/wrong files)

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#3383]
### Brief summary of bug

`ERR...clm-default` tests fail `COMPARE_base_rest`.

### General bug information

**CTSM version you are using:** `ctsm5.3.065-18-g0e9875d44` (commit `0e9875d4` on PR #3376)

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** `ERR...clm-default` tests, but _not_ `ERR...drv-interim_restart` test.

### Important details of your setup / configuration so we can reproduce the bug

Running the `interim_restart` test suite. Example at `/glade/derecho/scratch/samrabin/tests_0804-095600de/`.

### Important output or errors that show the problem
`./cs.status -s` gives:
```
  FAIL ERR_Ld7.f10_f10_mg37.I2000Clm50BgcCropRtm.derecho_intel.clm-default
  FAIL ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default
  PASS ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.drv-interim_restart
  PASS IRT_Ld11.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default
  PASS SMS_Ld5.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default
```

In `/glade/derecho/scratch/samrabin/tests_0804-095600de/ERR_Ld7.f10_f10_mg37.I2000Clm50BgcCropRtm.derecho_intel.clm-default.0804-095600de_int/TestStatus.log`:
```
  comparing model 'cpl'
    File 'ERR_Ld7.f10_f10_mg37.I2000Clm50BgcCropRtm.derecho_intel.clm-default.0804-095600de_int.cpl.hi.2000-01-08-00000.nc.base' had no compare counterpart in '/glade/derecho/scratch/samrabin/tests_0804-095600de/ERR_Ld7.f10_f10_mg37.I2000Clm50BgcCropRtm.derecho_intel.clm-default.0804-095600de_int/run' with suffix 'rest'
Did not compare any hist files! Missing baselines?
FAIL
WARNING
Expected to compare 3 hist files, but only compared 0. It's possible
that the hist_file_extension entry in config_archive.xml is not correct
for some of your components.
```

**Comment by samsrabin** [comment]
@slevis-lmwg [suggests](https://github.com/ESCOMP/CTSM/pull/3376#issuecomment-3151475121):
> Maybe you were already doing this:
> I think it makes sense for you to add the #3383 failure to the Expected Fails if you agree.

I'm not sure that's a good idea until we at least know what the problem is, especially since it fails with `clm-default`.

**Comment by ekluzek** [comment]
An example of a working test from CESM testing is this:

/glade/campaign/cesm/cesmdata/cseg/cesm_baselines/cesm3_0_alpha07b/ERR_Ld5.ne30pg3_t232.BLT1850.derecho_gnu.allactive-defaultio

An important thing there is that CPL history output there is 5 days, but it's 7 days for the test above.

I'm not sure why that might have to change, but It looks to me like doing this xmlchange should fix it...

``` shell
./xmlchange HIST_N=5
```

And as in the CESM test, you'll want to make sure mosart and rtm are outputing history files for this short run.

Try that and see if it fixes the test. Then the question is how to encapsulate that in a testmod that would work in a general way without fixing it based on the test run length....

**Comment by samsrabin** [comment]
How would that fix it, exactly? Would it be a real fix or just a kludge? I ask because the `drv-interim_restart` test also has `HIST_N=7` and it works fine.

`./xmlquery -p _N |grep "_N:"` in the working `ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.drv-interim_restart`:
```
	HIST_N: 7
	PAUSE_N: 0
	REST_N: 2
	STOP_N: 7
	SYSLOG_N: 900
```

And in the broken `ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default`:
```
	HIST_N: 7
	PAUSE_N: 0
	REST_N: 4
	STOP_N: 7
	SYSLOG_N: 900
```

**Comment by ekluzek** [comment]
> How would that fix it, exactly? Would it be a real fix or just a kludge? I ask because the `drv-interim_restart` test also has `HIST_N=7` and it works fine.

@samsrabin thanks for the correction. You are right I was comparing the wrong thing. I was comparing to the CESM baseline test which is 5 days.

I think the ERR test might require the drv-interim_restart testmod and/or it might only work for certain lengths. I have this as something to discuss in CSEG and hopefully we can get some help figuring it out then. I think I'll also ping Chris to see if we can have him do some testing here as well.

As long as HIST_N is set to the full run length, it seems to me this should work. So there's something I'm not understanding.

**Comment by samsrabin** [comment]
It may be that `ERR` does only work for some run lengths, but that's not the problem here. We know that because the working `drv-interim_restart` test has the same `Ld7` specifier as the broken `clm-default` tests.

I tried running the two failing tests with `./xmlchange --force REST_N=2` in `shell_commands` (i.e., the only thing in `drv/interim_restart`) and they still failed. Their `REST_N` was indeed set to 2. Thus, it doesn't seem to be that the `drv-interim_restart` testmod is actually required—I think something in `clm-default` is causing the problem. (Test suite directory: `/glade/derecho/scratch/samrabin/tests_0805-103342de/`)

**Comment by samsrabin** [comment]
...however, the `*cpl.hi.2000-01-08-00000.nc.rest` file _was_ found this time. So it fixed that. The problem now is that CLM files aren't being found. From `/glade/derecho/scratch/samrabin/tests_0805-103342de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de/TestStatus.log`:
```
2025-08-05 10:44:45: Comparing hists for case 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de' dir1='/glade/derecho/scratch/samrabin/tests_0805-103342de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de/run', suffix1='base',  dir2='/glade/derecho/scratch/samrabin/tests_0805-103342de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de/run' suffix2='rest'
  comparing model 'datm'
    no hist files found for model datm
  comparing model 'clm'
    File 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de.clm2.h0a.1850-01-08-00000.nc.base' had no compare counterpart in '/glade/derecho/scratch/samrabin/tests_0805-103342de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de/run' with suffix 'rest'
    File 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de.clm2.h0i.1850-01-08-00000.nc.base' had no compare counterpart in '/glade/derecho/scratch/samrabin/tests_0805-103342de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de/run' with suffix 'rest'
    File 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de.clm2.h1a.1850-01-08-00000.nc.base' had no compare counterpart in '/glade/derecho/scratch/samrabin/tests_0805-103342de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de/run' with suffix 'rest'
    File 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de.clm2.h0a.1850-01-12-00000.nc.rest' had no original counterpart in '/glade/derecho/scratch/samrabin/tests_0805-103342de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de/run' with suffix 'base'
    File 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de.clm2.h0i.1850-01-12-00000.nc.rest' had no original counterpart in '/glade/
derecho/scratch/samrabin/tests_0805-103342de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de/run' with suffix 'base'
    File 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de.clm2.h1a.1850-01-12-00000.nc.rest' had no original counterpart in '/glade/
derecho/scratch/samrabin/tests_0805-103342de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de/run' with suffix 'base'
  comparing model 'sice'
    no hist files found for model sice
  comparing model 'socn'
    no hist files found for model socn
  comparing model 'mosart'
    no hist files found for model mosart
  comparing model 'sglc'
    no hist files found for model sglc
  comparing model 'swav'
    no hist files found for model swav
  comparing model 'sesp'
    no hist files found for model sesp
  comparing model 'cpl'
    ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default.0805-103342de.cpl.hi.1850-01-08-00000.nc.base matched ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.d
erecho_intel.clm-default.0805-103342de.cpl.hi.1850-01-08-00000.nc.rest
```

**Comment by ekluzek** [comment]
YES! OK, fixed one problem. So the testmod is required so that the cplhist files are handled correctly.

The other problem is that the .rest extension is added to day 12 rather than 8 in the case2run. But, it's only running to day 8...

Hmmm...

**Comment by slevis-lmwg** [comment]
From meeting with @ekluzek @fischer-ncar @briandobbins 
- Erik suggested that we replicate the problem documented by Sam R.
- Chris will continue investigating from the coupled model perspective
- Sam L. suggested starting over making the ERR test from ERS (because that one we know works), and then adding whatever additional ERR is supposed to do. From the meeting 
1) ERR and ERS codes looked more different than I would have expected; they should mostly look the same
Out of curiosity and to replicate the ERR problem I submitted (test IDs 20250806_180717_mxydwl and 20250806_180651_68dai5)
```
PASS ERS_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default
FAIL ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default COMPARE_base_rest
```
and qstat already shows that ERR runs the archiver, while ERS does not
```
2233073.desche* slevis   cpu      test.ERR_*    --    1 128  235gb 12:00 Q   -- 
2233074.desche* slevis   cpudev   st_archiv*    --    1   1   10gb 00:20 H   -- 
2233075.desche* slevis   cpu      test.ERS_*    --    1 128  235gb 12:00 Q   --
```
2) Should the tests differ in any other way? Was there a time when ERR tests worked and could that help us find the problem?
3) At Thursday's CTSM software meeting (2025/8/7) we covered that we have a working ERR test and a failing one (ctsm-default), and we agreed to mark the latter as a low priority.

**Comment by samsrabin** [comment]
ERR tests were previously (before the CIME tag in #3376) unreliable, so if you want to do some bisection with them, make sure to apply the necessary fixes.

**Comment by samsrabin** [comment]
@jedwards4b I'm not sure if Erik contacted you after the CSEG meeting yesterday, but this is the remaining ERR failure we're seeing.

**Comment by ekluzek** [comment]
Thanks @samsrabin. @jedwards4b see some of the comments above to get an idea of what might be happening. It looks to me this is a problem in CIME, so I'll start an issue in CIME.

**Comment by jedwards4b** [comment]
I'll look into it - @ekluzek it would really be helpful if instead of just making pronouncements like "It looks to me this is a problem in CIME" you wrote down what the problem is that you think you are observing.

**Comment by ekluzek** [comment]
OK, the thing that makes me suspect CIME is the observation I made above:

https://github.com/ESCOMP/CTSM/issues/3383#issuecomment-3155994235

Which makes me think there's something strange happening with the test as it looks like the segments being compared are running over different sections. The base section runs to day 8, but the rest section runs to day 12.

**Comment by ekluzek** [comment]
OK, I also tried replicating what @samsrabin has above, which means including the drv-interim_restart testmod, as he included it by hand in ctsm5.3.068 and it PASSes for me.

ERS_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default--drv-interim_restart

So maybe there isn't a problem here?

**Comment by samsrabin** [comment]
@ekluzek The `drv-interim_restart` test is passing for me too; it's the `clm-default` tests that fail.

Run on ctsm5.3.069 with this testlist to replicate:
```
ERR_Ld7.f10_f10_mg37.I2000Clm50BgcCropRtm.derecho_intel.clm-default
ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default
ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.drv-interim_restart
```

**Comment by jedwards4b** [comment]
It looks to me like mosart is not writing a restart at end of run.   If you look at the archive directory you can see in
rest/1850-01-05-00000/ there is rpointer.rof.1850-01-05-00000 but there isn't one for 1850-01-08-00000.
I'm going to lunch now and will address this afterward.

**Comment by jedwards4b** [comment]
https://github.com/ESCOMP/MOSART/pull/124 should fix the problem, it was merged in mosart1.1.12 which is not in this branch.

**Comment by jedwards4b** [comment]
After fixing that I found the problem I think that you see - the restarts at time 1850-01-08-00000 should be compared but the 1850-01-11-00000 files are being copied from the case2run directory.

**Comment by ekluzek** [comment]
@samsrabin the test I did included BOTH drv-interim_restart AND clm-default which is what it looks to me what's required for this test. And I did it with ctsm5.3.068 which includes mosart1.1.12.

The fail for the plain default version is in the baseline here:

/glade/campaign/cgd/tss/ctsm_baselines/ctsm5.3.068/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default

The test directory is here:

/glade/campaign/cgd/tss/ctsm_baselines/ctsm5.3.068/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default

The problem there is that it didn't find files to compare, because there is no restarts until the end of the simulation. See this part of the TestStatus.log:

```
 ---------------------------------------------------
2025-08-11 11:53:16: Comparing hists for case 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu' dir1='/glade/derecho/scratch/slevis/tests_0811-105723de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu/run', suffix1='base',  dir2='/glade/derecho/scratch/slevis/tests_0811-105723de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu/run' suffix2='rest'
  comparing model 'datm'
    no hist files found for model datm
  comparing model 'clm'
    File 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu.clm2.h0a.1850-01-08-00000.nc.base' had no compare counterpart in '/glade/derecho/scratch/slevis/tests_0811-105723de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu/run' with suffix 'rest'
    File 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu.clm2.h0i.1850-01-08-00000.nc.base' had no compare counterpart in '/glade/derecho/scratch/slevis/tests_0811-105723de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu/run' with suffix 'rest'
    File 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu.clm2.h1a.1850-01-08-00000.nc.base' had no compare counterpart in '/glade/derecho/scratch/slevis/tests_0811-105723de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu/run' with suffix 'rest'
    File 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu.clm2.h0a.1850-01-11-00000.nc.rest' had no original counterpart in '/glade/derecho/scratch/slevis/tests_0811-105723de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu/run' with suffix 'base'
    File 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu.clm2.h0i.1850-01-11-00000.nc.rest' had no original counterpart in '/glade/derecho/scratch/slevis/tests_0811-105723de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu/run' with suffix 'base'
    File 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu.clm2.h1a.1850-01-11-00000.nc.rest' had no original counterpart in '/glade/derecho/scratch/slevis/tests_0811-105723de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu/run' with suffix 'base'
  comparing model 'sice'
    no hist files found for model sice
  comparing model 'socn'
    no hist files found for model socn
  comparing model 'mosart'
    no hist files found for model mosart
  comparing model 'sglc'
    no hist files found for model sglc
  comparing model 'swav'
    no hist files found for model swav
  comparing model 'sesp'
    no hist files found for model sesp
  comparing model 'cpl'
    File 'ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu.cpl.hi.1850-01-08-00000.nc.base' had no compare counterpart in '/glade/derecho/scratch/slevis/tests_0811-105723de/ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_gnu.clm-default.GC.0811-105723de_gnu/run' with suffix 'rest'
Did not compare any hist files! Missing baselines?
FAIL
WARNING
Expected to compare 3 hist files, but only compared 0. It's possible
that the hist_file_extension entry in config_archive.xml is not correct
for some of your components.
```

So I contend that leaving off the drv-interim_restart testmod results in an invalid test. @jedwards4b and others do you agree?

So the only thing to maybe add is something that would make this more obvious that it's an invalid test?

And can a few others verify that running the test that includes both -- works for them in ctsm5.3.068?

ERS_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default--drv-interim_restart

**Comment by ekluzek** [comment]
@jedwards4b and I just chatted and the problem is that the REST_N for the test WITHOUT the drv-interim_restart testmod is that it restarts from the end of the first simulation, which means there's no overlapping history files to compare. So right now the testmod is required. @jedwards4b said he knows what to do, so I presume he'll make the appropriate changes needed. I assume that might be cime and/or cmeps.

**Comment by jedwards4b** [comment]
Two changes required:

https://github.com/ESCOMP/CMEPS/pull/582
https://github.com/ESMCI/cime/pull/4831

The CMEPS change adds the ERR test to the list of tests that should avoid restarts at end of run.
The cime change corrects the math in computing the first available restart time.

**Comment by jedwards4b** [comment]
I have confirmed that both ERS_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default--drv-interim_restart and ERR_Ld7.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-default work with this change.

**Comment by ekluzek** [comment]
Awesome, thanks @jedwards4b! This sounds like a simple thing we should just bring on b4b-dev. But, I added next so we can discuss tomorrow on who will do this.

**Comment by ekluzek** [comment]
From looking back this just needed a CMEPS and cime update. So would've been fixed when that happened.
